repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=2048"]
          - id: check-yaml
            exclude: ^bamboo-specs/
          - id: check-json
          - id: check-toml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: check-merge-conflict
          - id: debug-statements
          - id: requirements-txt-fixer
          - id: check-executables-have-shebangs
    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.1.1
      hooks:
          - id: docker-compose-check
    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-no-log-warn
          - id: python-check-mock-methods
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.4.2
      hooks:
          - id: remove-tabs
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
    - repo: local
      hooks:
          - id: check
            name: Local repo make check (black, ruff, mypy)
            language: system
            entry: make check
            pass_filenames: false
